export { default as CalendarIcon } from './calendadr-icon.tsx';
export { default as HeartIcon } from './heart-icon.tsx';
export { default as TrophyIcon } from './trophy-icon.tsx';
export { default as ProfileIcon } from './profile-icon.tsx';
export { default as ExitIcon } from './exit-icon.tsx';
export { default as CollapsedOpenIcon } from './collapsed-open-icon.tsx';
export { default as CollapsedCloseIcon } from './collapsed-close-icon.tsx';
export { default as LogoDesktopIcon } from './logo-desktop-icon.tsx';
export { default as LogoMinIcon } from './logo-min-icon.tsx';
